## Introduction
1. В таблице реляционной базы данных PK используется для однозначной идентификации каждой строки в таблице. Следовательно, повторение PK в таблице не является допустимым, так как это создаст неоднозначность и приведет к конфликтам в уникальности данных.
2.  Redis относится к key-value базам данных, где работа с информацией организовано в форме хеш-таблицы. Особенность Redis заключается в том, что он предлагает высокую производительность и может использоваться в различных сценариях, таких как кэширование, очереди сообщений, сессии, аналитика и других. Также данные хранятся преимущественно в оперативной памяти. Это делает Redis особенно быстрым и эффективным для выполнения операций чтения и записи.
3.  MongoDB — документарная система управления базами данных. Считается одним из классических примеров NoSQL-систем, использует JSON-подобные документы и схему базы данных. Если в традиционном мире SQL есть таблицы, то в мире MongoDB есть **коллекции**. И если в реляционных БД таблицы хранят однотипные жестко структурированные объекты, то в коллекции могут содержать самые разные объекты, имеющие различную структуру и различный набор свойств. Аналогом строки/записи в MongoDB является **документ (document)**. Документ представляет собой JSON-подобный объект, который хранится в коллекции. Вот пример документа который может быть хранен в коллекции MongoDB.

```JSON
{
  "_id": ObjectId("60972a299cc1fa39a88be849"),
  "name": "Kirill Chernov",
  "age": 21,
  "email": "chernovkn@vk.com",
  "address": {
    "street": "Leninskie gory",
    "city": "Moscow",
  },
  "skills": ["Python", "DS", "SQL"]
}
```

 Значение `_id` представляет собой уникальный идентификатор документа, который MongoDB генерирует автоматически при его создании.

4.

- анализ поведения знаменитостей в социальной сети: В данном случае подходит графовая база данных, такая как Neo4j, которая хорошо подходит для хранения и анализа связей между данными.
- онлайн-аналитика действий пользователей на сайте онлайн магазина: Для хранения информации о клиентах, товарах и заказах подходит реляционная база данных, такая как PostgreSQL или MySQL, которые предоставляют возможность производить сложные операции агрегации и соединения таблиц.
- анализ документации по фильмам и сериалам: Здесь можно использовать реляционную базу данных, такую как PostgreSQL или MySQL, для хранения информации о фильмах и актерах.
- проектирование наиболее оптимальных маршрутов поставок для маркетплейса: Для оптимального проектирования маршрутов и выполнения операций геолокации подходит гео-распределенная база данных, такая как MongoDB с использованием геопространственных индексов и запросов.
- хранение кэшированных HTML страниц пользователей, посещающих сайт: В данном случае можно использовать кэш-базу данных, такую как Redis, например, для хранения кэшированных HTML страниц. Это позволит быстро получать готовые страницы из кэша без необходимости выполнения сложной логики и запросов к другим базам данных. данных.

## Data Manipulation Language
1. Порядок написания команд:
   1. SELECT
   2. FROM
   3. WHERE
   4. GROUP BY
   5. HAVING
   6. ORDER BY
   7. LIMIT
      
   Порядок выполнения команд:
   1. FROM
   2. WHERE
   3. GROUP BY
   4. HAVING
   5. SELECT
   6. ORDER BY
   7. LIMIT
2. Команда, позволяющая удалить строки таблицы по условию — это команда **DELETE**. Однако, команда DELETE используется для удаления строк таблицы, а не самой таблицы. Чтобы удалить таблицу, необходимо использовать команду **DROP TABLE**, указав имя таблицы.

3.
```sql
SELECT first_name, last_name FROM USERS
left join orders
ON orders.user_id = users.id 
where orders._order_date similar to '%/(9|10|11)/2022%' and orders.status = 'create_order'
LIMIT 1000;
```

4.
```sql
SELECT *, CASE WHEN price = (SELECT MAX(price) FROM orders) 
    THEN 10
    ELSE 0
END as discount,  CASE WHEN price = (SELECT MAX(price) FROM orders) 
    THEN price*0.9
    ELSE price
END as new_price
FROM orders
order by price DESC
limit 1000;
```

5.
```sql
DELETE FROM orders WHERE status = 'cancel_order' or items > 4;
```

6.
```sql
SELECT substring(email FROM E'@(.*)$') AS domain, count(1) FROM users
where gender = 'Male'
group by (domain)
order by count DESC 
limit 3;
```

7. Код, приведенный ниже не является полным SQL-запросом.
```sql
SELECT old_price - new_price AS diff 
FROM goods 
WHERE diff > 100
```

Этот код не будет работать в PostgreSQL, т.к. при выполнении запроса, столбцы, указанные в списке SELECT, не могут использоваться в условии WHERE в том же запросе. Это связано с тем, что в логическом порядке выполнения SQL-операций, специфическом для PostgreSQL, сначала обрабатывается условие WHERE, а затем выполняется список SELECT.